### ISSUE TITLE
Config.json missing

### ISSUE THREAD

**Issue by fardeen619** [Henry-Hiles/QuadraticBot2.0#1]
Hello i want to self host bot

**Comment by Henry-Hiles** [comment]
Hey there! Though it is easier to just invite the bot, it is possible to self-host. Just create a `config.json` file at the root of the project with a format like this. 
![image](https://user-images.githubusercontent.com/71790868/155026869-8974c09f-a9dd-4d64-9659-c920646fb608.png)
To get a client id and token register a new application here: https://discord.com/developers/applications

If you use the bot publicly please give credit in the bots description. Thank you.
