### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Akari0001** [Henry-Hiles/QuadraticBot2.0#11]
Add bonus role entry please 

Check out the giveaway bot https://dasu.gg

**Comment by Henry-Hiles** [comment]
Will do, do you mean like an entry multiplier for a role?

**Comment by Henry-Hiles** [comment]
Alr sounds good.

**Comment by Henry-Hiles** [comment]
A bit busy right now, but i will add this as soon as i have time.

**Comment by Henry-Hiles** [comment]
Really? What is it?

**Comment by Henry-Hiles** [comment]
> If the winner dm is off the giveaway will not end
> 
> Console says `cannot dm user`

Hey, i cannot reproduce this,for me it ends fine just doesnt dm  the user, if this is a problem, please open a new issue and use the bug report template.

**Comment by Henry-Hiles** [comment]
Should be fixed as of latest commit, thanks for letting me know. In the future for errors could you create a new issue with the bug report template?

**Comment by Henry-Hiles** [comment]
> Yep + i have a way for u to add bonus entries

What do you mean? My plan was to just push more to the array, but that would be a little weird with a large multiplier.

**Comment by Henry-Hiles** [comment]
It also makes it confusing on how to join the giveaway.

**Comment by Henry-Hiles** [comment]
Oh, then what was the button for?

**Comment by Henry-Hiles** [comment]
Oh the cinammon button. Hmm. What if i just add it in the embed?

**Comment by Henry-Hiles** [comment]
Yeah sorry 😅

Will try to add this week

**Comment by Henry-Hiles** [comment]
I have finished the migration to v14, and i implemented this feature. I will test and if all goes well will deploy on Tuesday night / Wednesday.

**Comment by Henry-Hiles** [comment]
Just pushed, should now be working.
