### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Akari0001** [Henry-Hiles/QuadraticBot2.0#15]
When ever i host a giveaway and the giveaway is active and i change the giveaway channel, the giveaway wont end

**Comment by Henry-Hiles** [comment]
Hmm, i see. Will try to fix this when i get back.

**Comment by Henry-Hiles** [comment]
OK, I see the issue, to fix i think i will loop through all channels, checking for messages.

**Comment by Henry-Hiles** [comment]
Though that doesnt seem very effecient thinking about it so i will just store channelId in the database.

**Comment by Henry-Hiles** [comment]
Should be fixed in latest release. Keep in mind that it will only work for giveaways created from now on. Present giveaways will not finish should the config be changed to another channel.
