### ISSUE TITLE
Slash cmds not loading

### ISSUE THREAD

**Issue by ANNACRAFTE** [Henry-Hiles/QuadraticBot2.0#2]
The bot comes online but the slash cmd isnt loading

**Comment by Henry-Hiles** [comment]
Are you selfhosting?

**Comment by Henry-Hiles** [comment]
If so did you make sure the bot had Application.Commands when inviting it?

**Comment by Henry-Hiles** [comment]
Otherwise, please elaborate.

**Comment by ANNACRAFTE** [comment]
> Are you selfhosting?

Yep i am

**Comment by ANNACRAFTE** [comment]
> If so did you make sure the bot had Application.Commands when inviting it?

Yes it was

**Comment by Henry-Hiles** [comment]
Did you make the config.json file correctly? Also arw there any logs?

**Comment by ANNACRAFTE** [comment]
> Did you make the config.json file correctly? Also arw there any logs?

Yep

**Comment by ANNACRAFTE** [comment]
Q:do you have discord

**Comment by ANNACRAFTE** [comment]
> Did you make the config.json file correctly? Also arw there any logs?

Yes there are logs

**Comment by Henry-Hiles** [comment]
> > Did you make the config.json file correctly? Also arw there any logs?
> 
> Yes there are logs

Upload the log please.

**Comment by Henry-Hiles** [comment]
> Q:do you have discord

If you don't mind I would prefer to continue here.

**Comment by ANNACRAFTE** [comment]
> > Q:do you have discord
> 
> If you don't mind I would prefer to continue here.

Alr

**Comment by ANNACRAFTE** [comment]
Ima restart brb

**Comment by ANNACRAFTE** [comment]
Q: what do u use to host the bot ?

**Comment by Henry-Hiles** [comment]
Also have you ran the `node deployCommands.js` commamd yet?

**Comment by ANNACRAFTE** [comment]
> Also have you ran the `node deployCommands.js` commamd yet?

Oop nope

**Comment by Henry-Hiles** [comment]
> > Also have you ran the `node deployCommands.js` commamd yet?
> 
> Oop nope

Ah that should fix iirc. If not please reopen.
