### ISSUE TITLE
Changes request

### ISSUE THREAD

**Issue by ANNACRAFTE** [Henry-Hiles/QuadraticBot2.0#3]
When i react to a giveaway i create its saying **you cant join your own giveaway**
But if i set role requirements andgive my self the required role its saying i joined

And can u put the channel & extra message option in the `/giveaway` cmd

**Comment by ANNACRAFTE** [comment]
And yes i fixed it i can now see all cmds ♡

**Comment by Henry-Hiles** [comment]
Oh will fix very soon, ty for making the issue

**Comment by Henry-Hiles** [comment]
Oops didnt mean to close

**Comment by Henry-Hiles** [comment]
Should now be fixed (Though i did this from my phone, so please lmk if the issue persists).
