### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Akarifromdiscord** [Henry-Hiles/QuadraticBot2.0#4]
Can u add a bonus role entry feature

**Comment by Henry-Hiles** [comment]
Could you please elaborate?

**Comment by Akarifromdiscord** [comment]
> Could you please elaborate?

Eg

Users with @Role role get 50x Entry chance

**Comment by Akarifromdiscord** [comment]
> Could you please elaborate?

Plus the bot has errors

**Comment by Henry-Hiles** [comment]
What errors?

**Comment by Akarifromdiscord** [comment]
> What errors?

https://media.discordapp.net/attachments/957953220297261096/970332928586432622/Screenshot_20220501-093015_Discord.jpg

I think ik why

**Comment by Akarifromdiscord** [comment]
I think i can fix it 🙂

**Comment by Henry-Hiles** [comment]
> > What errors?
> 
> https://media.discordapp.net/attachments/957953220297261096/970332928586432622/Screenshot_20220501-093015_Discord.jpg
> 
> I think ik why

Is this thr main bot or are you self-hosting?

**Comment by Akarifromdiscord** [comment]
> > > What errors?
> > 
> > 
> > https://media.discordapp.net/attachments/957953220297261096/970332928586432622/Screenshot_20220501-093015_Discord.jpg
> > I think ik why
> 
> Is this thr main bot or are you self-hosting?

The official bot

**Comment by Henry-Hiles** [comment]
> > What errors?
> 
> https://media.discordapp.net/attachments/957953220297261096/970332928586432622/Screenshot_20220501-093015_Discord.jpg
> 
> I think ik why

Hmm, why do you think?

**Comment by Akarifromdiscord** [comment]
> > > What errors?
> > 
> > 
> > https://media.discordapp.net/attachments/957953220297261096/970332928586432622/Screenshot_20220501-093015_Discord.jpg
> > I think ik why
> 
> Hmm, what do you think?

If i set it to 10 winners it will fail
But if its 1-2 it works fine

**Comment by Akarifromdiscord** [comment]
> > > > What errors?
> > > 
> > > 
> > > https://media.discordapp.net/attachments/957953220297261096/970332928586432622/Screenshot_20220501-093015_Discord.jpg
> > > I think ik why
> > 
> > 
> > Hmm, what do you think?
> 
> If i set it to 10 winners it will fail But if its 1-2 it works fine

Here is what i get when i self host
https://media.discordapp.net/attachments/970804853544747128/971178012169084948/Screenshot_20220430-081546_Chrome.jpg

**Comment by Henry-Hiles** [comment]
> 

Getting an error when trying to view this, let me try myself.

**Comment by Henry-Hiles** [comment]
Hmm cannot reproduce, though i can see the error in the main bots logs.

**Comment by Henry-Hiles** [comment]
looking at the db, it seems to be less then 10 winners sometimes...

**Comment by Akarifromdiscord** [comment]
What you can do is let it send more that one embed when a giveaway ends if its more than 1 winner

**Comment by Akarifromdiscord** [comment]
![Screenshot_20220505-190824_Bluecord](https://user-images.githubusercontent.com/101001006/167046262-da525283-e531-48aa-9e3b-df5b6354b33b.jpg)

**Comment by Akarifromdiscord** [comment]
+ its best to put the end and reroll command in slash commands for phone users because context menu for android isnt out yet

**Comment by Henry-Hiles** [comment]
> * its best to put the end and reroll command in slash commands for phone users because context menu for android isnt out yet

Going to wait for discord devs to implement that.

**Comment by Henry-Hiles** [comment]
As I don't want required developer mode.

**Comment by Akarifromdiscord** [comment]
> ![Screenshot_20220505-190824_Bluecord](https://user-images.githubusercontent.com/101001006/167046262-da525283-e531-48aa-9e3b-df5b6354b33b.jpg)

What about this?

**Comment by Henry-Hiles** [comment]
> > ![Screenshot_20220505-190824_Bluecord](https://user-images.githubusercontent.com/101001006/167046262-da525283-e531-48aa-9e3b-df5b6354b33b.jpg)
> 
> What about this?

You mewn no embed for one winner?

**Comment by Akarifromdiscord** [comment]
> > > ![Screenshot_20220505-190824_Bluecord](https://user-images.githubusercontent.com/101001006/167046262-da525283-e531-48aa-9e3b-df5b6354b33b.jpg)
> > 
> > 
> > What about this?
> 
> You mean no embed for one winner?

No like if its more that one winners eg 2 it will tag the two winners like in the image

**Comment by Henry-Hiles** [comment]
Oh i see what you mean, seperate messages.

**Comment by Henry-Hiles** [comment]
hmm, maybe i will add it as a config option soon.

**Comment by Henry-Hiles** [comment]
> > > > > What errors?
> > > > 
> > > > 
> > > > https://media.discordapp.net/attachments/957953220297261096/970332928586432622/Screenshot_20220501-093015_Discord.jpg
> > > > I think ik why
> > > 
> > > 
> > > Hmm, what do you think?
> > 
> > 
> > If i set it to 10 winners it will fail But if its 1-2 it works fine
> 
> Here is what i get when i self host https://media.discordapp.net/attachments/970804853544747128/971178012169084948/Screenshot_20220430-081546_Chrome.jpg

Could you fix this image please? Or can you tell me if it is that the entrant if not defined? What steps can you follow to reproduce?

**Comment by Henry-Hiles** [comment]
That bug should hopefully now be fixed. thank you.

**Comment by Henry-Hiles** [comment]
> * its best to put the end and reroll command in slash commands for phone users because context menu for android isnt out yet

Btw, this is now in discord beta if you join it.
