### ISSUE TITLE
Your changes make it hard to selfhost

### ISSUE THREAD

**Issue by Isabelle0001** [Henry-Hiles/QuadraticBot2.0#5]
Can u give me a guide on how to self host this

**Comment by Henry-Hiles** [comment]
It's pretty simple, what are you having trouble with?

**Comment by Akarifromdiscord** [comment]
The startup commands + the bug isn't fix it still not ending at the ending time in the official bot

**Comment by Henry-Hiles** [comment]
As for the bug, it should be fixed, and for the startup all you need to do is `pnpm i` `then node .`

**Comment by Henry-Hiles** [comment]
To install pnpm do `<sudo on linux> npm i -g pnpm`

**Comment by Henry-Hiles** [comment]
Nevermind, looking at the logs the error is still happening... The problem is i cannot reproduce... You say you can, exactly what do you do when this happens?

**Comment by Henry-Hiles** [comment]
I am going to make a seperate issue for this bug.

**Comment by Henry-Hiles** [comment]
> Not working have you try to self host your change?

Yes. What is your error?

**Comment by Henry-Hiles** [comment]
> > > Not working have you try to self host your change?
> > 
> > 
> > Yes. What is your error?
> 
> Giveaway not ending when I choose more than 1 winners

When self-hosting?

**Comment by Henry-Hiles** [comment]
> > > > > Not working have you try to self host your change?
> > > > 
> > > > 
> > > > Yes. What is your error?
> > > 
> > > 
> > > Giveaway not ending when I choose more than 1 winners
> > 
> > 
> > When self-hosting?
> 
> No in your bot

Oh, probably related to https://github.com/Henry-Hiles/QuadraticBot2.0/issues/6, unfortunately i cannot reproduce. I meant what error when self-hosting.

**Comment by Henry-Hiles** [comment]
I see, i cannot reproduce this error, i will keep trying.

**Comment by Henry-Hiles** [comment]
Thank you. Now if you can, please post some info, E.G. giveaway arguments in #6. :)
