### ISSUE TITLE
Giveaways not ending

### ISSUE THREAD

**Issue by Henry-Hiles** [Henry-Hiles/QuadraticBot2.0#6]
**Describe the bug**
Some giveaways do not end.

**To Reproduce**
Unknown.

**Expected behavior**
For the giveaway to end.

**Additional context**
The error seems to be the following: `
`TypeError: Cannot read properties of undefined (reading 'userId')

**Comment by Henry-Hiles** [comment]
No, just javascript.

**Comment by Henry-Hiles** [comment]
Yes i know, the entrant is undefined.

**Comment by Henry-Hiles** [comment]
What i do not know is why

**Comment by Henry-Hiles** [comment]
I think i will add some logs in and next time it happens i can check them.

**Comment by Henry-Hiles** [comment]
Will do tomorrow, thank you for your help.

**Comment by Henry-Hiles** [comment]
> Use optional chaining or add a check.

I would, but the thing is ir should never be `undefined`.

**Comment by Henry-Hiles** [comment]
> [check](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

Yes thank you, i know.

**Comment by Henry-Hiles** [comment]
Yeah.

**Comment by Henry-Hiles** [comment]
Yep.

**Comment by Henry-Hiles** [comment]
> * you need to push the changes you made to the original bot
> 
> 
> Bye now :)

What?

**Comment by Henry-Hiles** [comment]
Oh yeah i forgot to deply command, that shouldnt case it though. Anyway goodnight, i will attempt to fix this tomorroe, thank you.

**Comment by Henry-Hiles** [comment]
Not really rn. I have a server where i test the bot ehile selfhosting though.

**Comment by ANNACRAFTE** [comment]
Hello

**Comment by Henry-Hiles** [comment]
Hello, sorry for the delay, i believe i have now fixed it.

**Comment by Henry-Hiles** [comment]
Had a very busy week but managed to reproduce after making two alts. I believe you need to three people to join to reproduce

**Comment by Henry-Hiles** [comment]
The problem was that delete doesnt reindex the array. Using splice now.

**Comment by Henry-Hiles** [comment]
(If the error persists please reopen)
